<?php

namespace Andrey\RssReaderBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ChanelsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChanelsRepository extends EntityRepository
{
}
