andrey_my_sql_terminal:
    resource: "@AndreyMySqlTerminalBundle/Resources/config/routing.yml"
    prefix:   /

andrey_crud:
    resource: "@AndreyCrudBundle/Resources/config/routing.yml"
    prefix:   /