parameters:
#    andrey_examples.example.class: Andrey\ExamplesBundle\Example

services:
#    andrey_examples.example:
#        class: %andrey_examples.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
