andrey_rss_reader_homepage:
    pattern:  /rss_reader/
    defaults: { _controller: AndreyRssReaderBundle:Default:index }
andrey_rss_reader_allpage:
    pattern:  /rss_reader/all/
    defaults: { _controller: AndreyRssReaderBundle:Default:all }
andrey_rss_reader_sourcepage:
    pattern:  /rss_reader/source/
    defaults: { _controller: AndreyRssReaderBundle:Default:source }
andrey_rss_reader_sourcenewspage:
    pattern:  /rss_reader/sourcenews/{id}/
    defaults: { _controller: AndreyRssReaderBundle:Default:sourcenews }
andrey_rss_reader_newspage:
    pattern:  /rss_reader/news/{id}/
    defaults: { _controller: AndreyRssReaderBundle:Default:news }
andrey_rss_reader_updatepage:
    pattern:  /rss_reader/update/
    defaults: { _controller: AndreyRssReaderBundle:Default:update }
