parameters:
#    andrey_rss_reader.example.class: Andrey\RssReaderBundle\Example

services:
#    andrey_rss_reader.example:
#        class: %andrey_rss_reader.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
     RssReaderService.service:
         class: Andrey\RssReaderBundle\Services\RssReaderService
     Paginator.service:
         class: Andrey\RssReaderBundle\Services\Paginator
     RssReaderModel.model:
         class: Andrey\RssReaderBundle\Models\Model

