parameters:
#    andrey_rss_reader.example.class: Andrey\RssReaderBundle\Example

services:
     RssReaderService.service:
         class: Andrey\RssReaderBundle\Services\RssReaderService
         arguments: [@kernel, @Paginator.service, @RssReaderModel.model]
     Paginator.service:
         class: Andrey\RssReaderBundle\Services\Paginator
     RssReaderModel.model:
         class: Andrey\RssReaderBundle\Models\Model
         arguments: [@doctrine]

